default:
  image: node:latest

stages:
  - publish

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  key: "$CI_COMMIT_SHA"
  paths:
    - node_modules/

release:
  stage: publish
  script:
    - |
      if [ "${CI_SERVER_PORT}" = "443" ] || [ "${CI_SERVER_PORT}" = "80" ]
      then
        {
          echo '@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_SERVER_PROTOCOL}://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/'
          echo '//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}'
          echo '//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'
        } > .npmrc

        export GL_URL="${CI_SERVER_PROTOCOL}://${CI_SERVER_HOST}/api/v4"
      else
        {
          echo '@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_SERVER_PROTOCOL}://${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/'
          echo '//${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}'
          echo '//${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'
        } > .npmrc

        export GL_URL="${CI_SERVER_PROTOCOL}://${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4"
      fi

      export NPM_TOKEN=${CI_JOB_TOKEN}
      export NPM_CONFIG_REGISTRY="${GL_URL}/projects/${CI_PROJECT_ID}/packages/npm/"

      echo "GL_URL: ${GL_URL}"
      echo "NPM_CONFIG_REGISTRY: ${NPM_CONFIG_REGISTRY}"

      npm publish
